on:
  workflow_dispatch:
  push:

jobs:
  windows:
    name: Windows
    runs-on: windows-latest
    #runs-on: windows-2022
    #runs-on: windows-11-arm
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Find where node-gyp is preinstalled
        shell: bash
        run: |
          find $(dirname $(which node)) | grep node-gyp/package.json | xargs grep version

      - name: Upgrade node-gyp inside @npmcli/run-script package
        if: ${{ always() }}
        run: |
          $nodePath = Split-Path -Parent (Get-Command node).Path
          npm install --global --prefix $nodePath\\node_modules\\npm node-gyp@^11.2.0

      - name: npm install
        run: |
          npm ci
        env:
          # for ripgrep download
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # avoid slow downloads
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
          ELECTRON_SKIP_BINARY_DOWNLOAD: 1
          # node-gyp spawns one compiler by default
          JOBS: 'MAX'